### ISSUE TITLE
compilation fails at libosmoasn1rrc 

### ISSUE THREAD

**Issue by jbdu94** [E3V3A/gsm-parser#2]
Hi

compilation fails for me at:

`CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find libosmoasn1rrc (missing: LIBOSMO_ASN1_RRC_INCLUDE_DIR)
`
I cannot find this package via apt-get (debian, ubuntu, kali).
Any hint hos to solve this problem?

Thanks in advance for your help

**Comment by E3V3A** [comment]
This is 4 years outdated! 
Look at srlabs git site or better, look at the [compilation instructions for xlite](https://github.com/SnoopSnitch/xLite/blob/master/COMPILE.md). 
Anyway, just do: 
```bash
git clone http://opensource.srlabs.de/git/gsm-parser.git
```
